import type { Choice, InputSlot, LessonPractice, PracticeActivity, PracticeItem, PromptPart, RichText } from "./lesson-practice-types";

const page = (pageNo: number) => `../course-assets/by-lesson/lesson35/page${pageNo}.webp`;
const exerciseImage = (fileName: string) => `../data/book1_exercise_images/${fileName}`;
const audio = (exerciseNo: 1 | 2, order: number) => `https://japaflow-audio-bucket.oss-cn-shanghai.aliyuncs.com/textbook-audio/book1-unit9/lesson35/Exe${exerciseNo}_${order}.mp3`;
const text = (value: string, options: Omit<RichText, "type" | "text"> = {}): RichText => ({ type: "text", text: value, ...options });
const blank = (slotId: string): PromptPart => ({ type: "blank", slotId });
const wordSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "word", width: "medium", placeholder: "输入答案" }];
const sentenceSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "sentence", width: "long", placeholder: "输入完整句子" }];
const dialogueSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "dialogue", width: "long", multiline: true, rows: 5, placeholder: "输入完整会话" }];
const wordItem = (id: string, number: string, prompt: PromptPart[], promptKana: string, answer: string): PracticeItem => ({ id, number, prompt, promptKana, instruction: "", answerSource: "example_transform", evaluationMode: "exact", responseScope: "word_only", responseScopeHint: "填写括号中的词语。", inputSlots: wordSlot(), answer: { slotValues: { answer } } });
const sentenceItem = (id: string, number: string, prompt: string, promptKana: string, answer: string, source: PracticeItem["answerSource"] = "example_transform"): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana, instruction: "", answerSource: source, evaluationMode: "exact", responseScope: "sentence_only", responseScopeHint: "写出完整句子。", inputSlots: sentenceSlot(), answer: { slotValues: { answer } } });
const dialogueItem = (id: string, number: string, prompt: string, promptKana: string, answer: string): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana, instruction: "", answerSource: "audio", evaluationMode: "exact", responseScope: "dialogue_only", responseScopeHint: "写出完整会话。", inputSlots: dialogueSlot(), answer: { slotValues: { answer } }, renderHint: "dialogue" });
const choiceItem = (id: string, number: string, choices: Choice[], answerChoiceId: string): PracticeItem => ({ id, number, prompt: [text("听录音，选择对应答案。")], instruction: "", answerSource: "audio", evaluationMode: "exact", responseScope: "choice_only", choices, answer: { choiceIds: [answerChoiceId] }, renderHint: "inline" });
const conditionalItem = (id: string, number: string, prompt: string, promptKana: string, affirmative: string, negative: string): PracticeItem => ({ id, number, prompt: [text(`${prompt} → `), blank("affirmative"), text(" → "), blank("negative")], promptKana, instruction: "", answerSource: "example_transform", evaluationMode: "exact", responseScope: "word_only", responseScopeHint: "分别填写「～たら」和「～なかったら」的形式。", inputSlots: [{ id: "affirmative", expectedUnit: "word", width: "medium", placeholder: "肯定形" }, { id: "negative", expectedUnit: "word", width: "medium", placeholder: "否定形" }], answer: { slotValues: { affirmative, negative } } });

const listeningChoices: Choice[] = [
  { id: "c1", label: "① 雪が降りません" }, { id: "c2", label: "② 太りません" }, { id: "c3", label: "③ 運転してはいけません" }, { id: "c4", label: "④ 頑張ります" }, { id: "c5", label: "⑤ この本を読んでみてください" }, { id: "c6", label: "⑥ なかなか治りません" }, { id: "c7", label: "⑦ 中国に帰って働きます" }
];

const activities: PracticeActivity[] = [
  {
    id: "l35-p1-a1", section: "practice_1", order: 1, title: "仿照例句变换形式进行练习。然后听录音确认。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", requiresAudio: true,
    audio: { source: "textbook_exercise", url: audio(1, 1), label: "第35课 练习I-1", transcript: { source: "asr", confidenceNote: "ASR 覆盖例句及第 1—4 题；其余题目按教材给出的确定变形规则补全。", text: "[例] 雨が降ります。雨が降ったら。雨が降らなかったら。安いです。安かったら。安くなかったら。今月暇です。今月暇だったら。今月暇でなかったら。1 日本に行きます。日本に行ったら。日本に行かなかったら。2 かぎを見つけます。かぎを見つけたら。かぎを見つけなかったら。3 友達と話します。友達と話したら。友達と話さなかったら。4 優勝します。" , segments: [{ itemNumber: "1", text: "日本に行ったら。日本に行かなかったら。" }, { itemNumber: "2", text: "かぎを見つけたら。かぎを見つけなかったら。" }, { itemNumber: "3", text: "友達と話したら。友達と話さなかったら。" }, { itemNumber: "4", text: "優勝したら。優勝しなかったら。" }] } },
    layout: [{ type: "example", content: { label: "[例]", before: "雨が降ります\n安いです\n今月暇です", beforeKana: "あめがふります\nやすいです\nこんげつひまです", after: [text("雨が降ったら → 雨が降らなかったら\n安かったら → 安くなかったら\n今月暇だったら → 今月暇でなかったら", { kana: "あめがふったら → あめがふらなかったら\nやすかったら → やすくなかったら\nこんげつひまだったら → こんげつひまでなかったら" })], afterKana: "あめがふったら → あめがふらなかったら\nやすかったら → やすくなかったら\nこんげつひまだったら → こんげつひまでなかったら" } }],
    items: [
      conditionalItem("l35-p1-a1-q1", "1", "日本に行きます", "にほんにいきます", "日本に行ったら", "日本に行かなかったら"), conditionalItem("l35-p1-a1-q2", "2", "かぎを見つけます", "かぎをみつけます", "かぎを見つけたら", "かぎを見つけなかったら"), conditionalItem("l35-p1-a1-q3", "3", "友達と話します", "ともだちとはなします", "友達と話したら", "友達と話さなかったら"), conditionalItem("l35-p1-a1-q4", "4", "優勝します", "ゆうしょうします", "優勝したら", "優勝しなかったら"), conditionalItem("l35-p1-a1-q5", "5", "会社を休みます", "かいしゃをやすみます", "会社を休んだら", "会社を休まなかったら"), conditionalItem("l35-p1-a1-q6", "6", "ワインが残ります", "ワインがのこります", "ワインが残ったら", "ワインが残らなかったら"), conditionalItem("l35-p1-a1-q7", "7", "明日晴れます", "あしたはれます", "明日晴れたら", "明日晴れなかったら"), conditionalItem("l35-p1-a1-q8", "8", "お金があります", "おかねがあります", "お金があったら", "お金がなかったら"), conditionalItem("l35-p1-a1-q9", "9", "おじを訪ねます", "おじをたずねます", "おじを訪ねたら", "おじを訪ねなかったら"), conditionalItem("l35-p1-a1-q10", "10", "料理ができます", "りょうりができます", "料理ができたら", "料理ができなかったら"), conditionalItem("l35-p1-a1-q11", "11", "連絡します", "れんらくします", "連絡したら", "連絡しなかったら"), conditionalItem("l35-p1-a1-q12", "12", "台風が来ます", "たいふうがきます", "台風が来たら", "台風が来なかったら"), conditionalItem("l35-p1-a1-q13", "13", "暖かいです", "あたたかいです", "暖かかったら", "暖かくなかったら"), conditionalItem("l35-p1-a1-q14", "14", "カタログが欲しいです", "カタログがほしいです", "カタログが欲しかったら", "カタログが欲しくなかったら"), conditionalItem("l35-p1-a1-q15", "15", "成績がいいです", "せいせきがいいです", "成績がよかったら", "成績がよくなかったら"), conditionalItem("l35-p1-a1-q16", "16", "自由です", "じゆうです", "自由だったら", "自由でなかったら"), conditionalItem("l35-p1-a1-q17", "17", "有名です", "ゆうめいです", "有名だったら", "有名でなかったら"), conditionalItem("l35-p1-a1-q18", "18", "必要です", "ひつようです", "必要だったら", "必要でなかったら"), conditionalItem("l35-p1-a1-q19", "19", "雨です", "あめです", "雨だったら", "雨でなかったら"), conditionalItem("l35-p1-a1-q20", "20", "午前中です", "ごぜんちゅうです", "午前中だったら", "午前中でなかったら"), conditionalItem("l35-p1-a1-q21", "21", "宇宙飛行士です", "うちゅうひこうしです", "宇宙飛行士だったら", "宇宙飛行士でなかったら")
    ]
  },
  {
    id: "l35-p1-a2", section: "practice_1", order: 2, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [{ type: "example", content: { label: "[例]", before: "急に病気になります。", beforeKana: "きゅうにびょうきになります。", after: [text("もし急に病気になったら、どうしますか。", { kana: "もしきゅうにびょうきになったら、どうしますか。" })] } }],
    items: [sentenceItem("l35-p1-a2-q1", "1", "宝くじに当たります。", "たからくじにあたります。", "もし宝くじに当たったら、どうしますか。"), sentenceItem("l35-p1-a2-q2", "2", "外国でパスポートを落とします。", "がいこくでパスポートをおとします。", "もし外国でパスポートを落としたら、どうしますか。"), sentenceItem("l35-p1-a2-q3", "3", "馬さんが来ません。", "ばさんがきません。", "もし馬さんが来なかったら、どうしますか。"), sentenceItem("l35-p1-a2-q4", "4", "都合が悪いです。", "つごうがわるいです。", "もし都合が悪かったら、どうしますか。"), sentenceItem("l35-p1-a2-q5", "5", "パーティーが楽しくないです。", "パーティーがたのしくないです。", "もしパーティーが楽しくなかったら、どうしますか。"), sentenceItem("l35-p1-a2-q6", "6", "あなたが社長です。", "あなたがしゃちょうです。", "もしあなたが社長だったら、どうしますか。")]
  },
  {
    id: "l35-p1-a3", section: "practice_1", order: 3, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [{ type: "example", content: { label: "[例]", before: "明日都合がいいです／遊びに来てください", beforeKana: "あしたつごうがいいです／あそびにきてください", after: [text("明日都合がよかったら、遊びに来てください。", { kana: "あしたつごうがよかったら、あそびにきてください。" })] } }],
    items: [sentenceItem("l35-p1-a3-q1", "1", "工事の音がうるさいです／窓を閉めてください", "こうじのおとがうるさいです／まどをしめてください", "工事の音がうるさかったら、窓を閉めてください。"), sentenceItem("l35-p1-a3-q2", "2", "忙しくないです／いっしょにスケートに行きませんか", "いそがしくないです／いっしょにスケートにいきませんか", "忙しくなかったら、いっしょにスケートに行きませんか。"), sentenceItem("l35-p1-a3-q3", "3", "嫌いです／食べなくてもいいです", "きらいです／たべなくてもいいです", "嫌いだったら、食べなくてもいいです。"), sentenceItem("l35-p1-a3-q4", "4", "その仕事が終わります／休憩しましょう", "そのしごとがおわります／きゅうけいしましょう", "その仕事が終わったら、休憩しましょう。"), sentenceItem("l35-p1-a3-q5", "5", "反対です／手を挙げてください", "はんたいです／てをあげてください", "反対だったら、手を挙げてください。"), sentenceItem("l35-p1-a3-q6", "6", "困ります／営業の林さんに聞いてください", "こまります／えいぎょうのはやしさんにきいてください", "困ったら、営業の林さんに聞いてください。"), sentenceItem("l35-p1-a3-q7", "7", "みんながそろいます／会議を始めます", "みんながそろいます／かいぎをはじめます", "みんながそろったら、会議を始めます。"), sentenceItem("l35-p1-a3-q8", "8", "機会があります／世界旅行をしたいです", "きかいがあります／せかいりょこうをしたいです", "機会があったら、世界旅行をしたいです。")]
  },
  {
    id: "l35-p1-a4", section: "practice_1", order: 4, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "dialogue_practice", answerUnit: "dialogue", responseScope: "dialogue_only",
    layout: [{ type: "example", content: { label: "[例]", before: "安いです／買います\n子供です／安くなります", beforeKana: "やすいです／かいます\nこどもです／やすくなります", after: [text("甲：安かったら、買いますか。\n乙：いいえ、安くても買いません。\n甲：子供だったら安くなりますか。\n乙：いいえ、子供でも安くなりません。", { kana: "こう：やすかったら、かいますか。\nおつ：いいえ、やすくてもかいません。\nこう：こどもだったらやすくなりますか。\nおつ：いいえ、こどもでもやすくなりません。" })] } }],
    items: [dialogueItem("l35-p1-a4-q1", "1", "天気がいいです／出かけます", "てんきがいいです／でかけます", "甲：天気がよかったら、出かけますか。\n乙：いいえ、天気がよくても出かけません。"), dialogueItem("l35-p1-a4-q2", "2", "説明を聞きます／分かります", "せつめいをききます／わかります", "甲：説明を聞いたら、分かりますか。\n乙：いいえ、説明を聞いても分かりません。"), dialogueItem("l35-p1-a4-q3", "3", "暇です／サッカーを見に行きます", "ひまです／サッカーをみにいきます", "甲：暇だったら、サッカーを見に行きますか。\n乙：いいえ、暇でもサッカーを見に行きません。"), dialogueItem("l35-p1-a4-q4", "4", "友達です／今日来ます", "ともだちです／きょうきます", "甲：友達だったら、今日来ますか。\n乙：いいえ、友達でも今日来ません。")]
  },
  {
    id: "l35-p1-a5", section: "practice_1", order: 5, title: "仿照例句替换画线部分回答提问。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "answer_only", responseScopeHint: "只写回答句。",
    layout: [{ type: "example", content: { label: "[例 1]", before: "今年の夏休みは何日ですか。（３日）", beforeKana: "ことしのなつやすみはなんにちですか。（みっか）", after: [text("３日だけです。", { kana: "みっかだけです。" })] } }, { type: "example", content: { label: "[例 2]", before: "会議室にはだれがいますか。（李さん）", beforeKana: "かいぎしつにはだれがいますか。（りさん）", after: [text("李さんしかいません。", { kana: "りさんしかいません。" })] } }],
    items: [sentenceItem("l35-p1-a5-q1", "1", "今回の研修に参加するのは何人ですか。（２人）", "こんかいのけんしゅうにさんかするのはなんにんですか。（ふたり）", "２人だけです。"), sentenceItem("l35-p1-a5-q2", "2", "在庫はどのぐらいありますか。（２冊）", "ざいこはどのぐらいありますか。（にさつ）", "２冊だけあります。"), sentenceItem("l35-p1-a5-q3", "3", "日本語の授業はどのぐらいありますか。（１週間に１度）", "にほんごのじゅぎょうはどのぐらいありますか。（いっしゅうかんにいちど）", "１週間に１度だけあります。"), sentenceItem("l35-p1-a5-q4", "4", "来週いつ空いていますか。（火曜日）", "らいしゅういつあいていますか。（かようび）", "火曜日だけ空いています。"), sentenceItem("l35-p1-a5-q5", "5", "カラオケで何曲歌いましたか。（１曲）", "カラオケでなんきょくうたいましたか。（いっきょく）", "１曲だけ歌いました。"), sentenceItem("l35-p1-a5-q6", "6", "今いくらお金を持っていますか。（100円）", "いまいくらおかねをもっていますか。（ひゃくえん）", "100円だけ持っています。")].map((item) => ({ ...item, responseScope: "answer_only" as const, responseScopeHint: "只写回答句。" }))
  },
  {
    id: "l35-p1-a6", section: "practice_1", order: 6, title: "仿照例句，用（　）中的词语造句。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [{ type: "example", content: { label: "[例]", before: "会社を作ることができます（学生）", beforeKana: "かいしゃをつくることができます（がくせい）", after: [text("学生でも会社を作ることができます。", { kana: "がくせいでもかいしゃをつくることができます。" })] } }],
    items: [sentenceItem("l35-p1-a6-q1", "1", "この本を読むことができます（小学生）", "このほんをよむことができます（しょうがくせい）", "小学生でもこの本を読むことができます。"), sentenceItem("l35-p1-a6-q2", "2", "たくさん飲むのはよくないです（ビタミン剤）", "たくさんのむのはよくないです（ビタミンざい）", "ビタミン剤でもたくさん飲むのはよくないです。"), sentenceItem("l35-p1-a6-q3", "3", "食べ物が腐ります（冷蔵庫の中）", "たべものがくさります（れいぞうこのなか）", "冷蔵庫の中でも食べ物が腐ります。")]
  },
  {
    id: "l35-p1-a7", section: "practice_1", order: 7, title: "听录音，仿照例句替换画线部分练习会话。", instruction: "", interaction: "dialogue_practice", answerUnit: "dialogue", responseScope: "dialogue_only", requiresAudio: true,
    audio: { source: "textbook_exercise", url: audio(1, 7), label: "第35课 练习I-7", transcript: { source: "asr", confidenceNote: "ASR 覆盖例句及第 1—2 题；第 2 题的末轮回答按录音模式和教材替换词补全。", text: "[例] 問題が分かりません／先生に聞きます／友達。甲：問題が分からなかったら、どうしますか。乙：先生に聞きます。甲：友達はどうですか。乙：友達でも大丈夫です。1 パソコンが壊れます／新しいのを買います／中古パソコン。甲：パソコンが壊れたら、どうしますか。乙：新しいのを買います。甲：中古パソコンはどうですか。乙：中古パソコンでも大丈夫です。2 地震が起きます／まずドアを開けて、外へ逃げます／机の下。甲：地震が起きたら、どうしますか。乙：まずドアを開けて、外へ逃げます。", segments: [{ itemNumber: "1", text: "パソコンが壊れたら、どうしますか。新しいのを買います。中古パソコンはどうですか。中古パソコンでも大丈夫です。" }, { itemNumber: "2", text: "地震が起きたら、どうしますか。まずドアを開けて、外へ逃げます。机の下はどうですか。机の下でも大丈夫です。" }] } },
    layout: [{ type: "example", content: { label: "[例]", before: "問題が分かりません／先生に聞きます／友達", beforeKana: "もんだいがわかりません／せんせいにききます／ともだち", after: [text("甲：問題が分からなかったら、どうしますか。\n乙：先生に聞きます。\n甲：友達はどうですか。\n乙：友達でも大丈夫です。", { kana: "こう：もんだいがわからなかったら、どうしますか。\nおつ：せんせいにききます。\nこう：ともだちはどうですか。\nおつ：ともだちでもだいじょうぶです。" })] } }],
    items: [dialogueItem("l35-p1-a7-q1", "1", "パソコンが壊れます／新しいのを買います／中古パソコン", "パソコンがこわれます／あたらしいのをかいます／ちゅうこパソコン", "甲：パソコンが壊れたら、どうしますか。\n乙：新しいのを買います。\n甲：中古パソコンはどうですか。\n乙：中古パソコンでも大丈夫です。"), dialogueItem("l35-p1-a7-q2", "2", "地震が起きます／まずドアを開けて、外へ逃げます／机の下", "じしんがおきます／まずドアをあけて、そとへにげます／つくえのした", "甲：地震が起きたら、どうしますか。\n乙：まずドアを開けて、外へ逃げます。\n甲：机の下はどうですか。\n乙：机の下でも大丈夫です。")] 
  },
  {
    id: "l35-p2-a1", section: "practice_2", order: 1, title: "将（　）中的词语变成适当的形式完成句子。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only",
    layout: [{ type: "example", content: { label: "[例]", before: "駅に（着きます → 着いたら）、電話してください。", beforeKana: "えきに（つきます → ついたら）、でんわしてください。", after: [] } }],
    items: [wordItem("l35-p2-a1-q1", "1", [text("コンピュータを（使います → ", { kana: "コンピュータを（つかいます → " }), blank("answer"), text("）、電源を切っておいてください。", { kana: "）、でんげんをきっておいてください。" })], "コンピュータを（つかいます → ____）、でんげんをきっておいてください。", "使ったら"), wordItem("l35-p2-a1-q2", "2", [text("休暇を（取ることができます → ", { kana: "きゅうかを（とることができます → " }), blank("answer"), text("）、家族と旅行に行きたいと思います。", { kana: "）、かぞくとりょこうにいきたいとおもいます。" })], "きゅうかを（とることができます → ____）、かぞくとりょこうにいきたいとおもいます。", "取ることができたら"), wordItem("l35-p2-a1-q3", "3", [text("テレビの音が（うるさいです → "), blank("answer"), text("）、消してください。", { kana: "）、けしてください。" })], "テレビのおとが（うるさいです → ____）、けしてください。", "うるさかったら"), wordItem("l35-p2-a1-q4", "4", [text("（分かりません → ", { kana: "（わかりません → " }), blank("answer"), text("）、わたしに聞いてください。", { kana: "）、わたしにきいてください。" })], "（わかりません → ____）、わたしにきいてください。", "分からなかったら"), wordItem("l35-p2-a1-q5", "5", [text("雨が（降ります → ", { kana: "あめが（ふります → " }), blank("answer"), text("）、ピクニックは中止です。", { kana: "）、ピクニックはちゅうしです。" })], "あめが（ふります → ____）、ピクニックはちゅうしです。", "降ったら"), wordItem("l35-p2-a1-q6", "6", [text("10時に（来ません → ", { kana: "じゅうじに（きません → " }), blank("answer"), text("）、先に行きますよ。", { kana: "）、さきにいきますよ。" })], "じゅうじに（きません → ____）、さきにいきますよ。", "来なかったら")]
  },
  {
    id: "l35-p2-a2", section: "practice_2", order: 2, title: "听录音，从①～⑦中选择正确答案。", instruction: "", interaction: "single_choice", answerUnit: "choice", responseScope: "choice_only", requiresAudio: true,
    audio: { source: "textbook_exercise", url: audio(2, 2), label: "第35课 练习II-2", transcript: { source: "asr", confidenceNote: "ASR 在各题停顿处只识别到前半句；选择结果按录音句式与教材选项逐项对应。", text: "[例] 大学を卒業したら、中国に帰って働きます。1 仕事が大変でも。2 今年は冬になっても。3 暇だったら。4 いくら食べても。5 この薬を飲んでも。6 お酒を飲んだら。", segments: [{ itemNumber: "1", text: "仕事が大変でも、頑張ります。" }, { itemNumber: "2", text: "今年は冬になっても、雪が降りません。" }, { itemNumber: "3", text: "暇だったら、この本を読んでみてください。" }, { itemNumber: "4", text: "いくら食べても、太りません。" }, { itemNumber: "5", text: "この薬を飲んでも、なかなか治りません。" }, { itemNumber: "6", text: "お酒を飲んだら、運転してはいけません。" }] } },
    assets: [{ id: "l35-p2-a2-choice-bank", kind: "exercise_image", imagePath: exerciseImage("book1_lesson35_2_2.png"), label: "练习 II 2 选项框" }], displayAssets: ["l35-p2-a2-choice-bank"], layout: [{ type: "word_bank", words: [text("① 雪が降りません", { kana: "① ゆきがふりません" }), text("② 太りません", { kana: "② ふとりません" }), text("③ 運転してはいけません", { kana: "③ うんてんしてはいけません" }), text("④ 頑張ります", { kana: "④ がんばります" }), text("⑤ この本を読んでみてください", { kana: "⑤ このほんをよんでみてください" }), text("⑥ なかなか治りません", { kana: "⑥ なかなかなおりません" }), text("⑦ 中国に帰って働きます", { kana: "⑦ ちゅうごくにかえってはたらきます" })] }],
    items: [choiceItem("l35-p2-a2-q1", "1", listeningChoices, "c4"), choiceItem("l35-p2-a2-q2", "2", listeningChoices, "c1"), choiceItem("l35-p2-a2-q3", "3", listeningChoices, "c5"), choiceItem("l35-p2-a2-q4", "4", listeningChoices, "c2"), choiceItem("l35-p2-a2-q5", "5", listeningChoices, "c6"), choiceItem("l35-p2-a2-q6", "6", listeningChoices, "c3")]
  },
  {
    id: "l35-p2-a3", section: "practice_2", order: 3, title: "在______上填入适当的词语，完成句子。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only",
    layout: [{ type: "example", content: { label: "[例]", before: "日本では、熱があったら、お風呂に入りません。", beforeKana: "にほんでは、ねつがあったら、おふろにはいりません。", after: [] } }],
    items: [wordItem("l35-p2-a3-q1", "1", [text("風邪を"), blank("answer"), text("、病院へ行きます。", { kana: "、びょういんへいきます。" })], "かぜを____、びょういんへいきます。", "ひいたら"), wordItem("l35-p2-a3-q2", "2", [text("この靴は、いくら歩いても、足が", { kana: "このくつは、いくらあるいても、あしが" }), blank("answer"), text("。")], "このくつは、いくらあるいても、あしが____。", "痛くなります"), wordItem("l35-p2-a3-q3", "3", [text("いくら説明を"), blank("answer"), text("、使い方が分かりません。", { kana: "、つかいかたがわかりません。" })], "いくらせつめいを____、つかいかたがわかりません。", "聞いても"), wordItem("l35-p2-a3-q4", "4", [text("忙しいので、日曜日でも"), blank("answer"), text("。")], "いそがしいので、にちようびでも____。", "休みません")]
  },
  {
    id: "l35-p2-a4", section: "practice_2", order: 4, title: "给（　）中填入“しか”“だけ”“でも”，完成句子。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only",
    layout: [{ type: "example", content: { label: "[例]", before: "このお店にはクラシックのCD（しか）ありません。", beforeKana: "このおみせにはクラシックのシーディー（しか）ありません。", after: [] } }],
    items: [wordItem("l35-p2-a4-q1", "1", [text("わたしは毎朝コーヒー（", { kana: "わたしはまいあさコーヒー（" }), blank("answer"), text("）飲みません。", { kana: "）のみません。" })], "わたしはまいあさコーヒー（____）のみません。", "しか"), wordItem("l35-p2-a4-q2", "2", [text("この問題は子供（", { kana: "このもんだいはこども（" }), blank("answer"), text("）分かります。", { kana: "）わかります。" })], "このもんだいはこども（____）わかります。", "でも"), wordItem("l35-p2-a4-q3", "3", [text("会社でタバコを吸っているのは加藤さん（", { kana: "かいしゃでタバコをすっているのはかとうさん（" }), blank("answer"), text("）です。")], "かいしゃでタバコをすっているのはかとうさん（____）です。", "だけ")]
  },
  {
    id: "l35-p2-a5", section: "practice_2", order: 5, title: "将下面的句子译成日语。", instruction: "", interaction: "translation", answerUnit: "sentence", responseScope: "sentence_only", layout: [],
    items: [sentenceItem("l35-p2-a5-q1", "1", "大学毕业后有什么打算？——（我）想去外国工作。", "", "大学を卒業したらどうしますか。——外国で働きたいです。", "prompt"), sentenceItem("l35-p2-a5-q2", "2", "会议室只有小李一个人。", "", "会議室には李さんしかいません。", "prompt"), sentenceItem("l35-p2-a5-q3", "3", "回到日本也请继续学习汉语。", "", "日本へ帰っても、中国語の勉強を続けてください。", "prompt")]
  }
];

export const lesson35Practice: LessonPractice = {
  lessonId: "lesson35",
  title: "第35课 明日雨が降ったら、マラソン大会は中止です",
  sourcePages: [{ pageNo: 122, imagePath: page(122) }, { pageNo: 123, imagePath: page(123) }, { pageNo: 124, imagePath: page(124) }],
  activities
};
