import type { InputSlot, LessonPractice, PracticeActivity, PracticeItem, PromptPart, RichText } from "./lesson-practice-types";

const page = (pageNo: number) => `../course-assets/by-lesson/lesson36/page${pageNo}.webp`;
const exerciseImage = (fileName: string) => `../data/book1_exercise_images/${fileName}`;
const audio = (exerciseNo: 1 | 2, order: number) => `https://japaflow-audio-bucket.oss-cn-shanghai.aliyuncs.com/textbook-audio/book1-unit9/lesson36/Exe${exerciseNo}_${order}.mp3`;
const text = (value: string, options: Omit<RichText, "type" | "text"> = {}): RichText => ({ type: "text", text: value, ...options });
const blank = (slotId: string): PromptPart => ({ type: "blank", slotId });
const wordSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "word", width: "medium", placeholder: "输入答案" }];
const sentenceSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "sentence", width: "long", placeholder: "输入完整句子" }];
const dialogueSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "dialogue", width: "long", multiline: true, rows: 4, placeholder: "输入完整会话" }];
const sentenceItem = (id: string, number: string, prompt: string, promptKana: string, answer: string, source: PracticeItem["answerSource"] = "example_transform"): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana, instruction: "", answerSource: source, evaluationMode: "exact", responseScope: "sentence_only", responseScopeHint: "写出完整句子。", inputSlots: sentenceSlot(), answer: { slotValues: { answer } } });
const dialogueItem = (id: string, number: string, prompt: string, promptKana: string, answer: string): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana, instruction: "", answerSource: "audio", evaluationMode: "exact", responseScope: "dialogue_only", responseScopeHint: "写出完整会话。", inputSlots: dialogueSlot(), answer: { slotValues: { answer } }, renderHint: "dialogue" });
const wordItem = (id: string, number: string, prompt: PromptPart[], promptKana: string, answer: string, source: PracticeItem["answerSource"] = "example_transform"): PracticeItem => ({ id, number, prompt, promptKana, instruction: "", answerSource: source, evaluationMode: "exact", responseScope: "word_only", responseScopeHint: "填写括号中的词语。", inputSlots: wordSlot(), answer: { slotValues: { answer } } });
const transform = (id: string, number: string, before: string, kana: string, answer: string) => sentenceItem(id, number, before, kana, answer);

const activities: PracticeActivity[] = [
  {
    id: "l36-p1-a1", section: "practice_1", order: 1, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [], itemGroups: [
      { id: "l36-p1-a1-g1", example: { label: "[例 1]", before: "会議があります／行くことができません", beforeKana: "かいぎがあります／いくことができません", after: [text("会議があって、行くことができません。", { kana: "かいぎがあって、いくことができません。" })] }, items: [
        transform("l36-p1-a1-q1", "1", "ニュースを聞きました／びっくりしました", "ニュースをききました／びっくりしました", "ニュースを聞いて、びっくりしました。"), transform("l36-p1-a1-q2", "2", "孫が生まれました／喜んでいます", "まごがうまれました／よろこんでいます", "孫が生まれて、喜んでいます。"), transform("l36-p1-a1-q3", "3", "恋人にずっと会うことができません／悲しいです", "こいびとにずっとあうことができません／かなしいです", "恋人にずっと会うことができなくて、悲しいです。"), transform("l36-p1-a1-q4", "4", "漢字が分かりません／困っています", "かんじがわかりません／こまっています", "漢字が分からなくて、困っています。"), transform("l36-p1-a1-q5", "5", "雨にぬれました／風邪を引きました", "あめにぬれました／かぜをひきました", "雨にぬれて、風邪を引きました。")
      ] },
      { id: "l36-p1-a1-g2", example: { label: "[例 2]", before: "頭が痛いです／寝ています", beforeKana: "あたまがいたいです／ねています", after: [text("頭が痛くて、寝ています。", { kana: "あたまがいたくて、ねています。" })] }, items: [
        transform("l36-p1-a1-q6", "6", "都合が悪いです／出席しませんでした", "つごうがわるいです／しゅっせきしませんでした", "都合が悪くて、出席しませんでした。"), transform("l36-p1-a1-q7", "7", "うるさいです／李さんの声が聞こえません", "うるさいです／りさんのこえがきこえません", "うるさくて、李さんの声が聞こえません。"), transform("l36-p1-a1-q8", "8", "複雑です／時間がかかります", "ふくざつです／じかんがかかります", "複雑で、時間がかかります。"), transform("l36-p1-a1-q9", "9", "毎日会議です／忙しいです", "まいにちかいぎです／いそがしいです", "毎日会議で、忙しいです。"), transform("l36-p1-a1-q10", "10", "火事です／家が焼けました", "かじです／いえがやけました", "火事で、家が焼けました。")
      ] }
    ], items: []
  },
  {
    id: "l36-p1-a2", section: "practice_1", order: 2, title: "听录音，仿照例句替换画线部分进行练习。", instruction: "", interaction: "dialogue_practice", answerUnit: "dialogue", responseScope: "dialogue_only", requiresAudio: true,
    audio: { source: "textbook_exercise", url: audio(1, 2), label: "第36课 练习I-2", transcript: { source: "asr", confidenceNote: "ASR 覆盖例句及第1—2题；第3题按相同录音句式与教材替换词补全。", text: "[例] 鈴木さんが結婚しました／昨日聞きました。鈴木さんが結婚したのを知っていますか。ええ、昨日聞いて、びっくりしました。1 メキシコで大きな地震がありました／新聞で読みました。2 王さんが会社を辞めました／王さんからメールをもらいました。3 あの交差点で交通事故がありました／ニュースを見ました。", segments: [{ itemNumber: "1", text: "メキシコで大きな地震があったのを知っていますか。ええ、新聞で読んで、びっくりしました。" }, { itemNumber: "2", text: "王さんが会社を辞めたのを知っていますか。ええ、王さんからメールをもらって、びっくりしました。" }, { itemNumber: "3", text: "あの交差点で交通事故があったのを知っていますか。ええ、ニュースを見て、びっくりしました。" }] } },
    layout: [{ type: "example", content: { label: "[例]", before: "鈴木さんが結婚しました／昨日聞きました", beforeKana: "すずきさんがけっこんしました／きのうききました", after: [text("甲：鈴木さんが結婚したのを知っていますか。\n乙：ええ、昨日聞いて、びっくりしました。", { kana: "こう：すずきさんがけっこんしたのをしっていますか。\nおつ：ええ、きのうきいて、びっくりしました。" })] } }],
    items: [dialogueItem("l36-p1-a2-q1", "1", "メキシコで大きな地震がありました／新聞で読みました", "メキシコでおおきなじしんがありました／しんぶんでよみました", "甲：メキシコで大きな地震があったのを知っていますか。\n乙：ええ、新聞で読んで、びっくりしました。"), dialogueItem("l36-p1-a2-q2", "2", "王さんが会社を辞めました／王さんからメールをもらいました", "おうさんがかいしゃをやめました／おうさんからメールをもらいました", "甲：王さんが会社を辞めたのを知っていますか。\n乙：ええ、王さんからメールをもらって、びっくりしました。"), dialogueItem("l36-p1-a2-q3", "3", "あの交差点で交通事故がありました／ニュースを見ました", "あのこうさてんでこうつうじこがありました／ニュースをみました", "甲：あの交差点で交通事故があったのを知っていますか。\n乙：ええ、ニュースを見て、びっくりしました。")] 
  },
  {
    id: "l36-p1-a3", section: "practice_1", order: 3, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [], itemGroups: [
      { id: "l36-p1-a3-g1", example: { label: "[例 1]", before: "テープ／日本語の勉強／役立ちます", beforeKana: "テープ／にほんごのべんきょう／やくだちます", after: [text("テープは日本語の勉強に役立ちます。", { kana: "テープはにほんごのべんきょうにやくだちます。" })] }, items: [
        transform("l36-p1-a3-q1", "1", "秋／読書／いいです", "あき／どくしょ／いいです", "秋は読書にいいです。"), transform("l36-p1-a3-q2", "2", "デパート／買い物／便利です", "デパート／かいもの／べんりです", "デパートは買い物に便利です。"), transform("l36-p1-a3-q3", "3", "水泳／体／いいです", "すいえい／からだ／いいです", "水泳は体にいいです。"), transform("l36-p1-a3-q4", "4", "この軽いかばん／旅行／便利です", "このかるいかばん／りょこう／べんりです", "この軽いかばんは旅行に便利です。")
      ] },
      { id: "l36-p1-a3-g2", example: { label: "[例 2]", before: "パスポートを申請します／この写真を使います", beforeKana: "パスポートをしんせいします／このしゃしんをつかいます", after: [text("パスポートを申請するのに、この写真を使います。", { kana: "パスポートをしんせいするのに、このしゃしんをつかいます。" })] }, items: [
        transform("l36-p1-a3-q5", "5", "京都に行きます／よく新幹線を利用します", "きょうとにいきます／よくしんかんせんをりようします", "京都に行くのに、よく新幹線を利用します。"), transform("l36-p1-a3-q6", "6", "この本を書きます／２年かかりました", "このほんをかきます／にねんかかりました", "この本を書くのに２年かかりました。"), transform("l36-p1-a3-q7", "7", "日本文化を知ります／この本はとてもいいです", "にほんぶんかをしります／このほんはとてもいいです", "日本文化を知るのに、この本はとてもいいです。"), transform("l36-p1-a3-q8", "8", "生産コストを下げます／若い人を雇いました", "せいさんコストをさげます／わかいひとをやといました", "生産コストを下げるのに、若い人を雇いました。")
      ] }
    ], items: []
  },
  {
    id: "l36-p1-a4", section: "practice_1", order: 4, title: "仿照例句，看图回答录音中的提问。", instruction: "", interaction: "listening_answer", answerUnit: "sentence", responseScope: "answer_only", responseScopeHint: "只写回答句。", requiresAudio: true,
    audio: { source: "textbook_exercise", url: audio(1, 4), label: "第36课 练习I-4", transcript: { source: "asr", text: "これは何に使いますか。魚を切るのに使います。物を包むのに使います。自転車を修理するのに使います。お金を運ぶのに使います。", segments: [{ itemNumber: "1", text: "魚を切るのに使います。" }, { itemNumber: "2", text: "物を包むのに使います。" }, { itemNumber: "3", text: "自転車を修理するのに使います。" }, { itemNumber: "4", text: "お金を運ぶのに使います。" }] } },
    assets: [{ id: "l36-p1-a4-picture-cards", kind: "exercise_image", imagePath: exerciseImage("book1_lesson36_1_4.png"), label: "练习 I 4 图片" }], displayAssets: ["l36-p1-a4-picture-cards"], layout: [{ type: "example", content: { label: "[例]", before: "これは何に使いますか。（申請します）", beforeKana: "これはなににつかいますか。（しんせいします）", after: [text("パスポートを申請するのに使います。", { kana: "パスポートをしんせいするのにつかいます。" })] } }],
    items: [sentenceItem("l36-p1-a4-q1", "1", "魚／切ります", "さかな／きります", "魚を切るのに使います。", "audio"), sentenceItem("l36-p1-a4-q2", "2", "物／包みます", "もの／つつみます", "物を包むのに使います。", "audio"), sentenceItem("l36-p1-a4-q3", "3", "自転車／修理します", "じてんしゃ／しゅうりします", "自転車を修理するのに使います。", "audio"), sentenceItem("l36-p1-a4-q4", "4", "お金／運びます", "おかね／はこびます", "お金を運ぶのに使います。", "audio")].map(item => ({ ...item, responseScope: "answer_only" as const, responseScopeHint: "只写回答句。" }))
  },
  {
    id: "l36-p1-a5", section: "practice_1", order: 5, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [{ type: "example", content: { label: "[例]", before: "張さんはお酒を飲みます", beforeKana: "ちょうさんはおさけをのみます", after: [text("張さんはお酒を飲んでばかりいます。", { kana: "ちょうさんはおさけをのんでばかりいます。" })] } }],
    items: [transform("l36-p1-a5-q1", "1", "休みの日、森さんは寝ます", "やすみのひ、もりさんはねます", "休みの日、森さんは寝てばかりいます。"), transform("l36-p1-a5-q2", "2", "あの子は、いつも泣きます", "あのこは、いつもなきます", "あの子は、いつも泣いてばかりいます。"), transform("l36-p1-a5-q3", "3", "父は怒ります", "ちちはおこります", "父は怒ってばかりいます。"), transform("l36-p1-a5-q4", "4", "サッカーをしています", "サッカーをしています", "サッカーをしてばかりいます。"), transform("l36-p1-a5-q5", "5", "漫画を読んでいます", "まんがをよんでいます", "漫画を読んでばかりいます。"), transform("l36-p1-a5-q6", "6", "甘い物を食べています", "あまいものをたべています", "甘い物を食べてばかりいます。")]
  },
  {
    id: "l36-p1-a6", section: "practice_1", order: 6, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only",
    layout: [], itemGroups: [
      { id: "l36-p1-a6-g1", example: { label: "[例 1]", before: "富士山", beforeKana: "ふじさん", after: [text("家から富士山が見えます。", { kana: "いえからふじさんがみえます。" })] }, items: ["東京タワー", "海", "わたしの学校", "工場の煙突"].map((prompt, i) => transform(`l36-p1-a6-q${i + 1}`, String(i + 1), prompt, ["とうきょうタワー", "うみ", "わたしのがっこう", "こうじょうのえんとつ"][i], `家から${prompt}が見えます。`)) },
      { id: "l36-p1-a6-g2", example: { label: "[例 2]", before: "音楽", beforeKana: "おんがく", after: [text("隣の部屋から音楽が聞こえます。", { kana: "となりのへやからおんがくがきこえます。" })] }, items: ["森さんの声", "機械の音", "テレビの音", "子供の笑い声"].map((prompt, i) => transform(`l36-p1-a6-q${i + 5}`, String(i + 5), prompt, ["もりさんのこえ", "きかいのおと", "テレビのおと", "こどものわらいごえ"][i], `隣の部屋から${prompt}が聞こえます。`)) },
      { id: "l36-p1-a6-g3", example: { label: "[例 3]", before: "公園／戴さんが太極拳をしています／見えます", beforeKana: "こうえん／たいさんがたいきょくけんをしています／みえます", after: [text("公園で戴さんが太極拳をしているのが見えます。", { kana: "こうえんでたいさんがたいきょくけんをしているのがみえます。" })] }, items: [transform("l36-p1-a6-q9", "9", "どこか／ピアノを弾いています／聞こえます", "どこか／ピアノをひいています／きこえます", "どこかでピアノを弾いているのが聞こえます。"), transform("l36-p1-a6-q10", "10", "隣の部屋／歌を歌っています／聞こえます", "となりのへや／うたをうたっています／きこえます", "隣の部屋で歌を歌っているのが聞こえます。"), transform("l36-p1-a6-q11", "11", "グラウンド／森さんが野球をしています／見えます", "グラウンド／もりさんがやきゅうをしています／みえます", "グラウンドで森さんが野球をしているのが見えます。"), transform("l36-p1-a6-q12", "12", "屋上／張さんが手を振っています／見えます", "おくじょう／ちょうさんがてをふっています／みえます", "屋上で張さんが手を振っているのが見えます。")] }
    ], items: []
  },
  {
    id: "l36-p2-a1", section: "practice_2", order: 1, title: "从______中选择适当的词语，变成适当的形式填入（　）中。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only",
    assets: [{ id: "l36-p2-a1-word-bank", kind: "exercise_image", imagePath: exerciseImage("book1_lesson36_2_1.png"), label: "练习 II 1 词框" }], displayAssets: ["l36-p2-a1-word-bank"], layout: [{ type: "example", content: { label: "[例]", before: "太郎君が野球をしているのを昨日初めて（見ました）。", beforeKana: "たろうくんがやきゅうをしているのをきのうはじめて（みました）。", after: [] } }, { type: "word_bank", words: [text("見えます", { kana: "みえます" }), text("聞こえます", { kana: "きこえます" }), text("見ます", { kana: "みます" }), text("聞きます", { kana: "ききます" })] }],
    items: [wordItem("l36-p2-a1-q1", "1", [text("ここから兄が太極拳をしているのが（", { kana: "ここからあにがたいきょくけんをしているのが（" }), blank("answer"), text("）。")], "ここからあにがたいきょくけんをしているのが（____）。", "見えます"), wordItem("l36-p2-a1-q2", "2", [text("中国が優勝したニュースを（", { kana: "ちゅうごくがゆうしょうしたニュースを（" }), blank("answer"), text("）、みんな喜びました。", { kana: "）、みんなよろこびました。" })], "ちゅうごくがゆうしょうしたニュースを（____）、みんなよろこびました。", "聞いて"), wordItem("l36-p2-a1-q3", "3", [text("そのボタンを右に回すと、よく（", { kana: "そのボタンをみぎにまわすと、よく（" }), blank("answer"), text("）よ。")], "そのボタンをみぎにまわすと、よく（____）よ。", "聞こえます")]
  },
  { id: "l36-p2-a2", section: "practice_2", order: 2, title: "将（　）中的词语变成“～て”“～で”“～から”的形式，完成句子。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", layout: [{ type: "example", content: { label: "[例]", before: "手紙を（読みます → 読んで）、びっくりしました。", beforeKana: "てがみを（よみます → よんで）、びっくりしました。", after: [] } }], items: [wordItem("l36-p2-a2-q1", "1", [text("（遅くなります → ", { kana: "（おそくなります → " }), blank("answer"), text("）、すみません。", { kana: "）、すみません。" })], "（おそくなります → ____）、すみません。", "遅くなって"), wordItem("l36-p2-a2-q2", "2", [text("（寒いです → ", { kana: "（さむいです → " }), blank("answer"), text("）、窓を開けないで。", { kana: "）、まどをあけないで。" })], "（さむいです → ____）、まどをあけないで。", "寒くて"), wordItem("l36-p2-a2-q3", "3", [text("わたしの犬が（交通事故です → ", { kana: "わたしのいぬが（こうつうじこです → " }), blank("answer"), text("）、死にました。", { kana: "）、しにました。" })], "わたしのいぬが（こうつうじこです → ____）、しにました。", "交通事故で"), wordItem("l36-p2-a2-q4", "4", [text("（危ないです → ", { kana: "（あぶないです → " }), blank("answer"), text("）、やめなさい。")], "（あぶないです → ____）、やめなさい。", "危なくて"), wordItem("l36-p2-a2-q5", "5", [text("（熱です → ", { kana: "（ねつです → " }), blank("answer"), text("）、頭が痛いです。", { kana: "）、あたまがいたいです。" })], "（ねつです → ____）、あたまがいたいです。", "熱で")] },
  { id: "l36-p2-a3", section: "practice_2", order: 3, title: "在（　）中填入一个平假名。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", layout: [{ type: "example", content: { label: "[例]", before: "わたしは紅茶（が）好きです。", beforeKana: "わたしはこうちゃ（が）すきです。", after: [] } }], items: [wordItem("l36-p2-a3-q1", "1", [text("会社の場所を説明する（", { kana: "かいしゃのばしょをせつめいする（" }), blank("answer"), text("）に地図が要ります。", { kana: "）にちずがいります。" })], "かいしゃのばしょをせつめいする（____）にちずがいります。", "の"), wordItem("l36-p2-a3-q2", "2", [text("雪（"), blank("answer"), text("）電車が止まっています。", { kana: "）でんしゃがとまっています。" })], "ゆき（____）でんしゃがとまっています。", "で"), wordItem("l36-p2-a3-q3", "3", [text("この機械は何（", { kana: "このきかいはなに（" }), blank("answer"), text("）使いますか。", { kana: "）つかいますか。" })], "このきかいはなに（____）つかいますか。", "に"), wordItem("l36-p2-a3-q4", "4", [text("そこから李さん（", { kana: "そこからりさん（" }), blank("answer"), text("）見えますか。", { kana: "）みえますか。" })], "そこからりさん（____）みえますか。", "が"), wordItem("l36-p2-a3-q5", "5", [text("いくら聞いて（", { kana: "いくらきいて（" }), blank("answer"), text("）、何も言わないんです。", { kana: "）、なにもいわないんです。" })], "いくらきいて（____）、なにもいわないんです。", "も")] },
  { id: "l36-p2-a4", section: "practice_2", order: 4, title: "听录音，在（　）中填入适当的词语。", instruction: "", interaction: "listening_repeat", answerUnit: "word", responseScope: "word_only", requiresAudio: true, audio: { source: "textbook_exercise", url: audio(2, 4), label: "第36课 练习II-4", transcript: { source: "manual", text: "わたしは新しい家に引っ越しました。子供は小学生ですが、学校までは10分しかかかりません。家の前に静かな公園があって、とてもいい所です。何でも売っているスーパーも近くにあります。生活するのに便利で、気に入っています。\n\nでも、会社に8時半に着くために、6時半に家を出なければなりません。それに、家を買うのに3,000万円払いました。」", translation: "我搬到了新家。孩子是小学生，不过到学校只需要10分钟。家门前有一个安静的公园，是个非常不错的地方。附近还有一家什么都卖的超市。生活起来很方便，我很喜欢这里。不过，为了8点半到公司，我必须6点半就从家里出发。而且，为了买这套房子，我花了3000万日元。”", segments: [{ itemNumber: "1", text: "公園" }, { itemNumber: "2", text: "スーパー" }, { itemNumber: "3", text: "２" }, { itemNumber: "4", text: "3,000万" }] } }, layout: [], items: [wordItem("l36-p2-a4-q1", "1", [text("わたしが引っ越した家は、子供の学校や（", { kana: "わたしがひっこしたいえは、こどものがっこうや（" }), blank("answer"), text("）や（"), blank("answer2"), text("）が近くて、とても便利です。")], "わたしがひっこしたいえは、こどものがっこうや（____）や（____）がちかくて、とてもべんりです。", "公園", "audio"), wordItem("l36-p2-a4-q2", "2", [text("家から会社まで（", { kana: "いえからかいしゃまで（" }), blank("answer"), text("）時間かかるし、", { kana: "）じかんかかるし、" })], "いえからかいしゃまで（____）じかんかかるし、", "２", "audio"), wordItem("l36-p2-a4-q3", "3", [text("買うのに（", { kana: "かうのに（" }), blank("answer"), text("）円かかりましたが、とても気に入っています。", { kana: "）えんかかりましたが、とてもきにいっています。" })], "かうのに（____）えんかかりましたが、とてもきにいっています。", "3,000万", "audio")].map(item => item.id === "l36-p2-a4-q1" ? ({ ...item, renderHint: "dual_word", inputSlots: [{ id: "answer", expectedUnit: "word", width: "medium", placeholder: "输入答案" }, { id: "answer2", expectedUnit: "word", width: "medium", placeholder: "输入答案" }], answer: { slotValues: { answer: "公園", answer2: "スーパー" } } }) : item) },
  { id: "l36-p2-a5", section: "practice_2", order: 5, title: "将下面的句子译成日语。", instruction: "", interaction: "translation", answerUnit: "sentence", responseScope: "sentence_only", layout: [], items: [sentenceItem("l36-p2-a5-q1", "1", "老陈，明天的联欢会（你）去吗？——不行，明天（我）有工作，去不了。", "", "陳さん、明日のパーティーに行きますか。——いいえ、明日は仕事で、行くことができません。", "prompt"), sentenceItem("l36-p2-a5-q2", "2", "这张照片申请护照用。", "", "この写真はパスポートの申請に使います。", "prompt"), sentenceItem("l36-p2-a5-q3", "3", "可以看到机场的入口处站着警官。", "", "空港の入り口に警官が立っているのが見えます。", "prompt")] }
];

export const lesson36Practice: LessonPractice = { lessonId: "lesson36", title: "第36课 遅くなって、すみません", sourcePages: [{ pageNo: 132, imagePath: page(132) }, { pageNo: 133, imagePath: page(133) }, { pageNo: 134, imagePath: page(134) }], activities };
