import type { InputSlot, LessonPractice, PracticeActivity, PracticeItem, PromptPart, RichText } from "./lesson-practice-types";

const page = (pageNo: number) => `../course-assets/by-lesson/lesson32/page${pageNo}.webp`;
const exerciseImage = (fileName: string) => `../data/book1_exercise_images/${fileName}`;
const audio = (exerciseNo: 1 | 2, order: number) => `https://japaflow-audio-bucket.oss-cn-shanghai.aliyuncs.com/textbook-audio/book1-unit8/lesson32/Exe${exerciseNo}_${order}.mp3`;
const text = (value: string, options: Omit<RichText, "type" | "text"> = {}): RichText => ({ type: "text", text: value, ...options });
const blank = (slotId: string): PromptPart => ({ type: "blank", slotId });
const wordSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "word", width: "medium", placeholder: "输入答案" }];
const sentenceSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "sentence", width: "long", placeholder: "输入完整句子" }];
const dialogueSlot = (): InputSlot[] => [{ id: "answer", expectedUnit: "dialogue", width: "long", multiline: true, rows: 5, placeholder: "输入完整会话" }];
const wordItem = (id: string, number: string, prompt: string, kana: string, answer: string, source: "audio" | "prompt" = "prompt"): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana: kana, instruction: "", answerSource: source, evaluationMode: "exact", responseScope: "word_only", responseScopeHint: "填写括号中的词语。", inputSlots: wordSlot(), answer: { slotValues: { answer } } });
const sentenceItem = (id: string, number: string, prompt: string, kana: string, answer: string, source: "audio" | "example_transform" | "prompt" = "example_transform"): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana: kana, instruction: "", answerSource: source, evaluationMode: "exact", responseScope: "sentence_only", responseScopeHint: "写出完整句子。", inputSlots: sentenceSlot(), answer: { slotValues: { answer } } });
const dialogueItem = (id: string, number: string, prompt: string, kana: string, answer: string): PracticeItem => ({ id, number, prompt: [text(prompt)], promptKana: kana, instruction: "", answerSource: "prompt", evaluationMode: "exact", responseScope: "dialogue_only", responseScopeHint: "写出完整会话。", inputSlots: dialogueSlot(), answer: { slotValues: { answer } }, renderHint: "dialogue" });
const activities: PracticeActivity[] = [
  { id: "l32-p1-a1", section: "practice_1", order: 1, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only", layout: [{ type: "example", content: { label: "[例]", before: "今度のボーナスで車を買います。", beforeKana: "こんどのボーナスでくるまをかいます。", after: [text("今度のボーナスで車を買うつもりです。", { kana: "こんどのボーナスでくるまをかうつもりです。" })] } }], items: [sentenceItem("l32-p1-a1-q1", "1", "土曜日にデパートへ行きます。", "どようびにデパートへいきます。", "土曜日にデパートへ行くつもりです。"), sentenceItem("l32-p1-a1-q2", "2", "正月休みに友達に会います。", "しょうがつやすみにともだちにあいます。", "正月休みに友達に会うつもりです。"), sentenceItem("l32-p1-a1-q3", "3", "夏休みに車の運転を習います。", "なつやすみにくるまのうんてんをならいます。", "夏休みに車の運転を習うつもりです。"), sentenceItem("l32-p1-a1-q4", "4", "来週香港へ買い物に行きます。", "らいしゅうほんこんへかいものにいきます。", "来週香港へ買い物に行くつもりです。")] },
  { id: "l32-p1-a2", section: "practice_1", order: 2, title: "仿照例句，回答录音中的提问。", instruction: "", interaction: "listening_answer", answerUnit: "sentence", responseScope: "answer_only", requiresAudio: true, audio: { source: "textbook_exercise", url: audio(1, 2), label: "第32课 练习I-2", transcript: { source: "asr", text: "ボーナスで何を買いますか。車。車を買うつもりです。夏休み、どこへ行きますか。タイ。タイへ行くつもりです。明日、何をしますか。野球。野球をするつもりです。東京で誰に会いますか。周先生。周先生に会うつもりです。今日はお酒を飲まないんですか。はい、飲みません。はい、飲まないつもりです。" } }, layout: [], itemGroups: [
    { id: "l32-p1-a2-g1", example: { label: "[例1]", before: "ボーナスで何を買いますか。（車）", beforeKana: "ボーナスでなにをかいますか。（くるま）", after: [text("車を買うつもりです。", { kana: "くるまをかうつもりです。" })] }, items: [
      sentenceItem("l32-p1-a2-q1", "1", "タイ", "タイ", "タイへ行くつもりです。", "audio"),
      sentenceItem("l32-p1-a2-q2", "2", "野球", "やきゅう", "野球をするつもりです。", "audio"),
      sentenceItem("l32-p1-a2-q3", "3", "周先生", "しゅうせんせい", "周先生に会うつもりです。", "audio")
    ].map((item) => ({ ...item, responseScope: "answer_only", responseScopeHint: "听录音并结合给出的词语，只写回答句。" })) },
    { id: "l32-p1-a2-g2", example: { label: "[例2]", before: "今日はお酒を飲まないんですか。（はい／飲みません）", beforeKana: "きょうはおさけをのまないんですか。（はい／のみません）", after: [text("はい、飲まないつもりです。", { kana: "はい、のまないつもりです。" })] }, items: [
      sentenceItem("l32-p1-a2-q4", "4", "はい／しません", "はい／しません", "はい、しないつもりです。", "audio"),
      sentenceItem("l32-p1-a2-q5", "5", "はい／吸いません", "はい／すいません", "はい、吸わないつもりです。", "audio"),
      sentenceItem("l32-p1-a2-q6", "6", "はい／行きません", "はい／いきません", "はい、行かないつもりです。", "audio")
    ].map((item) => ({ ...item, responseScope: "answer_only", responseScopeHint: "听录音并结合给出的词语，只写回答句。" })) }
  ], items: [] },
  { id: "l32-p1-a3", section: "practice_1", order: 3, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only", layout: [{ type: "example", content: { label: "[例1]", before: "飛行機で行きます。", beforeKana: "ひこうきでいきます。", after: [text("飛行機で行くことにしました。", { kana: "ひこうきでいくことにしました。" })] } }], items: [sentenceItem("l32-p1-a3-q1", "1", "大阪で乗り換えます。", "おおさかでのりかえます。", "大阪で乗り換えることにしました。"), sentenceItem("l32-p1-a3-q2", "2", "会社を辞めます。", "かいしゃをやめます。", "会社を辞めることにしました。"), sentenceItem("l32-p1-a3-q3", "3", "清水さんと結婚します。", "しみずさんとけっこんします。", "清水さんと結婚することにしました。"), sentenceItem("l32-p1-a3-q4", "4", "旅行に行きません。", "りょこうにいきません。", "旅行に行かないことにしました。"), sentenceItem("l32-p1-a3-q5", "5", "車を買いません。", "くるまをかいません。", "車を買わないことにしました。"), sentenceItem("l32-p1-a3-q6", "6", "もうお酒を飲みません。", "もうおさけをのみません。", "もうお酒を飲まないことにしました。"), sentenceItem("l32-p1-a3-q7", "7", "東京に支店を作ります。", "とうきょうにしてんをつくります。", "東京に支店を作ることになりました。"), sentenceItem("l32-p1-a3-q8", "8", "給料が上がります。", "きゅうりょうがあがります。", "給料が上がることになりました。"), sentenceItem("l32-p1-a3-q9", "9", "今年から土曜日も休みます。", "ことしからどようびもやすみます。", "今年から土曜日も休むことになりました。"), sentenceItem("l32-p1-a3-q10", "10", "6時まで働かなければなりません。", "ろくじまではたらかなければなりません。", "6時まで働かなければならないことになりました。"), sentenceItem("l32-p1-a3-q11", "11", "加藤さんが冷蔵庫をくれます。", "かとうさんがれいぞうこをくれます。", "加藤さんが冷蔵庫をくれることになりました。"), sentenceItem("l32-p1-a3-q12", "12", "ここでタバコを吸ってはいけません。", "ここでタバコをすってはいけません。", "ここでタバコを吸ってはいけないことになりました。")] },
  { id: "l32-p1-a4", section: "practice_1", order: 4, title: "仿照例句替换画线部分进行练习。", instruction: "", interaction: "pattern_substitution", answerUnit: "sentence", responseScope: "sentence_only", layout: [{ type: "example", content: { label: "[例]", before: "北海道で大きな地震がありました。", beforeKana: "ほっかいどうでおおきなじしんがありました。", after: [text("ニュースによると、北海道で大きな地震があったそうです。", { kana: "ニュースによると、ほっかいどうでおおきなじしんがあったそうです。" })] } }], items: [sentenceItem("l32-p1-a4-q1", "1", "首相は来月アメリカに行きます。", "しゅしょうはらいげつアメリカにいきます。", "ニュースによると、首相は来月アメリカに行くそうです。"), sentenceItem("l32-p1-a4-q2", "2", "牛乳の値段が上がります。", "ぎゅうにゅうのねだんがあがります。", "ニュースによると、牛乳の値段が上がるそうです。"), sentenceItem("l32-p1-a4-q3", "3", "今年の冬はあまり寒くないです。", "ことしのふゆはあまりさむくないです。", "ニュースによると、今年の冬はあまり寒くないそうです。"), sentenceItem("l32-p1-a4-q4", "4", "風が強いので、飛行機が飛びません。", "かぜがつよいので、ひこうきがとびません。", "ニュースによると、風が強いので、飛行機が飛ばないそうです。"), sentenceItem("l32-p1-a4-q5", "5", "新型のパソコンは操作が簡単です。", "しんがたのパソコンはそうさがかんたんです。", "ニュースによると、新型のパソコンは操作が簡単だそうです。"), sentenceItem("l32-p1-a4-q6", "6", "大統領が女優と結婚しました。", "だいとうりょうがじょゆうとけっこんしました。", "ニュースによると、大統領が女優と結婚したそうです。")] },
  { id: "l32-p1-a5", section: "practice_1", order: 5, title: "仿照例句替换画线部分练习会话。", instruction: "", interaction: "dialogue_practice", answerUnit: "dialogue", responseScope: "dialogue_only", layout: [{ type: "example", content: { label: "[例]", before: "戴さんは日本料理を食べます／寿司が好きです／大丈夫です", beforeKana: "たいさんはにほんりょうりをたべます／すしがすきです／だいじょうぶです", after: [text("甲：戴さんは日本料理を食べるでしょうか。\n乙：寿司が好きだそうですから、大丈夫でしょう。", { kana: "こう：たいさんはにほんりょうりをたべるでしょうか。\nおつ：すしがすきだそうですから、だいじょうぶでしょう。" })] } }], items: [dialogueItem("l32-p1-a5-q1", "1", "森さんは明日来ます／都合が悪いです／来ません", "もりさんはあしたきます／つごうがわるいです／きません", "甲：森さんは明日来るでしょうか。\n乙：都合が悪いそうですから、来ないでしょう。"), dialogueItem("l32-p1-a5-q2", "2", "陳さんは教え方が上手です／学校の先生でした／上手です", "ちんさんはおしえかたがじょうずです／がっこうのせんせいでした／じょうずです", "甲：陳さんは教え方が上手でしょうか。\n乙：学校の先生だったそうですから、上手でしょう。"), dialogueItem("l32-p1-a5-q3", "3", "李さんはあの番組を見ました／歴史に興味があります／見ました", "りさんはあのばんぐみをみました／れきしにきょうみがあります／みました", "甲：李さんはあの番組を見たでしょうか。\n乙：歴史に興味があるそうですから、見たでしょう。"), dialogueItem("l32-p1-a5-q4", "4", "張さんは合格しました／試験は簡単でした／合格しました", "ちょうさんはごうかくしました／しけんはかんたんでした／ごうかくしました", "甲：張さんは合格したでしょうか。\n乙：試験は簡単だったそうですから、合格したでしょう。"), dialogueItem("l32-p1-a5-q5", "5", "明日は雨です／台風が来ています／雨です", "あしたはあめです／たいふうがきています／あめです", "甲：明日は雨でしょうか。\n乙：台風が来ているそうですから、雨でしょう。")] },
  { id: "l32-p1-a6", section: "practice_1", order: 6, title: "看下面的便条，仿照例句回答录音中的提问。", instruction: "", interaction: "listening_answer", answerUnit: "sentence", responseScope: "answer_only", requiresAudio: true, audio: { source: "textbook_exercise", url: audio(1, 6), label: "第32课 练习I-6", transcript: { source: "asr", text: "明日、何時に出発することになりましたか。午前8時に出発することになりました。何で行くつもりですか。車で行くつもりです。次の会議はどこで行うことになりましたか。京都で行うことになりました。いつからいつまで行うことになりましたか。9月1日から7日まで行うことになりました。劉英さんは何で行くことにしましたか。新幹線で行くことにしました。劉英さんは誰と食事をするつもりですか。佐藤さんと食事をするつもりです。" } }, assets: ["1", "2", "3"].map((n) => ({ id: `l32-p1-a6-note-${n}`, kind: "exercise_image" as const, imagePath: exerciseImage(`book1_lesson32_6_${n}.png`), label: `练习 I 6 便条 ${n}` })), displayAssets: ["l32-p1-a6-note-1", "l32-p1-a6-note-2", "l32-p1-a6-note-3"], layout: [], items: [sentenceItem("l32-p1-a6-q1", "1", "听录音，回答问题。", "", "京都で行うことになりました。", "audio"), sentenceItem("l32-p1-a6-q2", "2", "听录音，回答问题。", "", "9月1日から7日まで行うことになりました。", "audio"), sentenceItem("l32-p1-a6-q3", "3", "听录音，回答问题。", "", "新幹線で行くことにしました。", "audio"), sentenceItem("l32-p1-a6-q4", "4", "听录音，回答问题。", "", "佐藤さんと食事をするつもりです。", "audio")].map((item) => ({ ...item, responseScope: "answer_only", responseScopeHint: "只写回答句。" })) },
  { id: "l32-p2-a1", section: "practice_2", order: 1, title: "将（　）中的词语变成适当的形式，完成句子。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", layout: [{ type: "example", content: { label: "[例]", before: "ニュースによると、首相は（病気です → 病気だ）そうです。", beforeKana: "ニュースによると、しゅしょうは（びょうきです → びょうきだ）そうです。", after: [text("")] } }], items: [["馬さんは猫が（大好きです → ", "）そうです。", "大好きだ"], ["天気予報によると、明日は（晴れます → ", "）そうです。", "晴れる"], ["明日は（雨です → ", "）かもしれません。", "雨"], ["戴さんはあの新しい本屋へもう（行きました → ", "）そうです。", "行った"], ["あまり勉強しなかったから、息子は（合格しません → ", "）かもしれません。", "合格しない"], ["来月新しいコンピュータが出るので、今は（買いません → ", "）つもりです。", "買わない"]].map(([before, after, answer], index) => ({ id: `l32-p2-a1-q${index + 1}`, number: String(index + 1), prompt: [text(before), blank("answer"), text(after)], promptKana: "", instruction: "", answerSource: "prompt", evaluationMode: "exact", responseScope: "word_only", responseScopeHint: "填写箭头后的词语。", inputSlots: wordSlot(), answer: { slotValues: { answer } } })) },
  { id: "l32-p2-a2", section: "practice_2", order: 2, title: "在（　）中填入适当的疑问词。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", layout: [{ type: "example", content: { label: "[例]", before: "夏は（何時）からお店を開けますか。——8時から開けることにしました。", beforeKana: "なつは（なんじ）からおみせをあけますか。——はちじからあけることにしました。", after: [text("")] } }], items: [wordItem("l32-p2-a2-q1", "1", "夏休みに（　）へ行きますか。", "なつやすみに（　）へいきますか。", "どこ"), wordItem("l32-p2-a2-q2", "2", "（　）が手伝ってくれるんですか。", "（　）がてつだってくれるんですか。", "だれ"), wordItem("l32-p2-a2-q3", "3", "（　）昼ご飯を食べるんですか。", "（　）ひるごはんをたべるんですか。", "いつ"), wordItem("l32-p2-a2-q4", "4", "次の企画は（　）が担当するんですか。", "つぎのきかくは（　）がたんとうするんですか。", "だれ")] },
  { id: "l32-p2-a3", section: "practice_2", order: 3, title: "从框中选择适当的词语填入（　）中。", instruction: "", interaction: "fill_blank", answerUnit: "word", responseScope: "word_only", assets: [{ id: "l32-p2-a3-word-bank", kind: "exercise_image", imagePath: exerciseImage("book1_lesson32_2_3.png"), label: "练习 II 3 词框" }], displayAssets: ["l32-p2-a3-word-bank"], layout: [{ type: "word_bank", words: [text("そろそろ"), text("たまに"), text("さっき"), text("ところで"), text("必ず")] }], items: [wordItem("l32-p2-a3-q1", "1", "11時です。（　）帰りましょう。", "じゅういちじです。（　）かえりましょう。", "そろそろ"), wordItem("l32-p2-a3-q2", "2", "これは大切な書類ですから、（　）返してください。", "これはたいせつなしょるいですから、（　）かえしてください。", "必ず"), wordItem("l32-p2-a3-q3", "3", "あまりカラオケに行きませんが、（　）行くこともあります。", "あまりカラオケにいきませんが、（　）いくこともあります。", "たまに"), wordItem("l32-p2-a3-q4", "4", "王さんは結婚しているそうですね。（　）、あなたはどうなんですか。", "おうさんはけっこんしているそうですね。（　）、あなたはどうなんですか。", "ところで")] },
  { id: "l32-p2-a4", section: "practice_2", order: 4, title: "听录音中的会话，回答提问。", instruction: "", interaction: "listening_answer", answerUnit: "sentence", responseScope: "answer_only", requiresAudio: true, audio: { source: "textbook_exercise", url: audio(2, 4), label: "第32课 练习II-4", transcript: { source: "asr", text: "いつ、中田さんと会うことになりましたか。大阪へ何で行くことにしましたか。仕事が終わってから何をするつもりですか。来週、大阪に出張なんです。水曜日の午前中に中田さんと会うことにしました。朝早いので飛行機で行こうと思います。京都は今、桜がきれいだそうです。京都と大阪は近いですから見に行こうと思います。" } }, layout: [{ type: "example", content: { label: "[例]", before: "王さんはどこに出張しますか。", beforeKana: "おうさんはどこにしゅっちょうしますか。", after: [text("大阪です。", { kana: "おおさかです。" })] } }], items: [sentenceItem("l32-p2-a4-q1", "1", "听录音，回答问题。", "", "水曜日の午前中に中田さんと会うことにしました。", "audio"), sentenceItem("l32-p2-a4-q2", "2", "听录音，回答问题。", "", "飛行機で行くことにしました。", "audio"), sentenceItem("l32-p2-a4-q3", "3", "听录音，回答问题。", "", "京都へ桜を見に行こうと思います。", "audio")].map((item) => ({ ...item, responseScope: "answer_only", responseScopeHint: "只写回答句。" })) },
  { id: "l32-p2-a5", section: "practice_2", order: 5, title: "将下面的句子译成日语。", instruction: "", interaction: "translation", answerUnit: "sentence", responseScope: "sentence_only", layout: [], items: [sentenceItem("l32-p2-a5-q1", "1", "我打算用这次的奖金买车。", "", "今度のボーナスで車を買うつもりです。", "prompt"), sentenceItem("l32-p2-a5-q2", "2", "明天和朋友去看电影。", "", "明日、友達と映画を見に行くことにしました。", "prompt"), sentenceItem("l32-p2-a5-q3", "3", "据报道今年冬天流行流感。", "", "ニュースによると、今年の冬はインフルエンザが流行するそうです。", "prompt")] }
];

export const lesson32Practice: LessonPractice = { lessonId: "lesson32", title: "第32课 今度の日曜日に遊園地へ行くつもりです", sourcePages: [{ pageNo: 86, imagePath: page(86), label: "练习 I" }, { pageNo: 87, imagePath: page(87), label: "练习 I" }, { pageNo: 88, imagePath: page(88), label: "练习 II" }], activities };
